name:                major-server
version:             0.1.0.0
github:              "githubuser/major-server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/major-server#readme>

dependencies:
- base
- array
- MissingH
- bytestring
- extra
# - postgresql-simple
- resource-pool
- containers
- wai
- http-types
- configurator
- wai-cors
- scotty
- aeson
- wai-extra
- wai-middleware-auth
- wai-middleware-static
- random >= 1.2
- transformers
- text
- time
- vector
- random-shuffle
- scientific
- optparse-applicative

library:
  source-dirs: src

executables:
  major-server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - major-server

tests:
  major-server-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - major-server
