name:                major
version:             1.0
github:              "cloudyhug/major"
license:             MIT
author:              "cloudyhug"
maintainer:          "cloudyhug@protonmail.ch"
copyright:           "cloudyhug"

description:         Please see the README on GitHub at <https://github.com/cloudyhug/major#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2.1
- scotty >= 0.11.6
- bytestring >= 0.10.10.1
- text >= 1.2.4.0
- brick >= 0.52.1
- regex-base >= 0.94.0.0
- regex-pcre >= 0.95.0.0
- array >= 0.5.4.0
- http-conduit >= 2.3.7.3
- http-types >= 0.12.3
- http-client >= 0.6.4.1
- vty >= 5.28.2
- process >= 1.6.9.0
- aeson >= 1.4.7.1
- random >= 1.1
- hashable >= 1.3.0.0
- wai-cors >= 0.2.7

library:
  source-dirs: common

executables:
  major-server:
    main:                Main.hs
    source-dirs:         app/server
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - major
  # major-client:
  #   main:                Main.hs
  #   source-dirs:         app/client
  #   ghc-options:
  #     - -threaded
  #     - -rtsopts
  #     - -with-rtsopts=-N
  #   dependencies:
  #     - major
